version: "3.8"

services:
  backend:
    build: ./backend
    container_name: todo-app-backend
    ports:
      - "4999:4999"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: todo-app-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
